services:
  - type: web
    name: removedor-fundo-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: REMBG_MODEL
        value: u2net
      - key: CORS_ORIGINS
        value: "*"
